name: Build IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install tools
        run: |
          brew install apktool

      - name: Extract APK
        run: |
          chmod +x scripts/extract.sh
          ./scripts/extract.sh

      - name: Create iOS App
        run: |
          chmod +x scripts/create_ios.sh
          ./scripts/create_ios.sh

      - name: Build IPA
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: ipa
          path: build/*.ipa
